{{- if .Values.postgres.enabled }}
{{- with .Values.postgres }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  labels:
    role: postgress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .volumeSize | default "10gi" }}
{{- end }}
{{- end }}
