{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "helm.labels" . | nindent 4 }}
{{- with .Values.postgres }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
{{- end }}
{{- end }}