# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  image:
    image:
    pullSecrets: []
    repository: corbancloud/ph-witw
    pullPolicy: IfNotPresent
    tag: "latest"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000

postgres:
  enabled: true
  image:
    pullSecrets: []
    repository: corbancloud/ph-witw-db
    pullPolicy: IfNotPresent
    tag: "latest"
  resources: {}
  service:
    port: 5432
  volumeSize: "10gi"

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []