-- AlterTable
ALTER TABLE "City" ALTER COLUMN "alternate_names" DROP NOT NULL,
ALTER COLUMN "feature_class" DROP NOT NULL,
ALTER COLUMN "feature_code" DROP NOT NULL,
ALTER COLUMN "cc2" DROP NOT NULL,
ALTER COLUMN "admin1_code" DROP NOT NULL,
ALTER COLUMN "admin2_code" DROP NOT NULL,
ALTER COLUMN "admin3_code" DROP NOT NULL,
ALTER COLUMN "admin4_code" DROP NOT NULL;
