name: CD

on:
    - pull_request

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: build
              run: docker build -t frankh/witw:$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH") .
            - name: push
              run: docker push frankh/witw:$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
